### PR TITLE
Fully support multiple forwarding DNS servers by trying all of them

### PR DESCRIPTION
**Pull request by febbraro**
Turns out that the support for multiple forwarding name servers was never fully implemented correctly. It only tried the first configured name server and then returned regardless of result.   

This PR will return on a success and otherwise will try the next configured name server until there are none left.

### CODE REVIEW

**Comment by febbraro** [comment]
Not sure what this is failing on, but it is no change that I introduced. How do we prompt for a rebuild?

**Comment by aacebedo** [comment]
You can retrigger a build by pushing your branch but the problem is somewhere else. Anyway your commit looks good I am merging it :)

**Comment by aacebedo** [comment]
Well done !

**Comment by febbraro** [comment]
Thanks!

**Pull request merged**
