### PR TITLE
feature: cache services dns path, fix issue 91

### PR DESCRIPTION
**Pull request by dsalahutdinov**
Hi. Sorry for unfinished PR.
I just want somebody to review it first 😄 
This is the try of solving this issue https://github.com/aacebedo/dnsdock/issues/91

Common idea is to cache dns names as treen, it allows to navigate faster and to resolve names correctly

### CODE REVIEW

**Comment by dsalahutdinov** [comment]
Is anybody here to maintain?

**Comment by aacebedo** [comment]
Yo

i'm going tout review this soon. Regards

**Comment by aacebedo** [comment]
Hi !

I am currently integrating your fix but I see that the tests are not valid.
I'll have to fix them before releasing your change.

Regards

**Comment by dsalahutdinov** [comment]
Hi, Thanks for response!
Do you want me to fix all the tests? I can make it

**Comment by aacebedo** [comment]
Dont sorry I am fixing it :)
Behaviour has changed a little but I thing the new one is more correct in comparison with the previous.

Regards

**Pull request merged**
